language: python

sudo: false

addons:
  apt:
    update: true
    packages:
      - curl
      - git

script:
  - ls -al
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - mkdir test
  - cd test
  - echo "Doing ~/bin/repo init -u ../ -b $TRAVIS_BRANCH"
  - echo "Doesn't work yet in Travis ~/bin/repo --color=never init -u ../"
  - ~/bin/repo --color=never version
